import React, { useState } from "react";
import { getPatientInfo, getMedicines, getDietPlan, getPrescriptionHistory } from "../data/mockDatabase";

function ShareWithDoctor({ data, onClose }) {
  const [isDownloading, setIsDownloading] = useState(false);
  
  // Use mock database data if data prop is not provided
  const patientInfo = data?.patient || getPatientInfo();
  const medicines = data?.medicines || getMedicines();
  const dietPlan = data?.diet || getDietPlan();
  const prescriptionHistory = getPrescriptionHistory();

  const handleDownloadPDF = () => {
    setIsDownloading(true);
    // Mock PDF download - Generate report using mock database
    setTimeout(() => {
      setIsDownloading(false);
      
      // Create a simple text report (mock PDF)
      const reportContent = `
HEALTH REPORT - ${new Date().toLocaleDateString()}

PATIENT INFORMATION:
Name: ${patientInfo.name}
Age: ${patientInfo.age} years
Condition: ${patientInfo.condition}
Blood Group: ${patientInfo.bloodGroup}

CURRENT MEDICATIONS:
${medicines.map((med, i) => `${i + 1}. ${med.name} - ${med.dosage} (${med.time})`).join('\n')}

DIET PLAN:
Foods to Eat: ${dietPlan.eat.join(', ')}
Foods to Avoid: ${dietPlan.avoid.join(', ')}

PRESCRIPTION HISTORY:
${prescriptionHistory.slice(0, 3).map(p => `- ${p.date}: ${p.doctor} - ${p.condition}`).join('\n')}

Generated by AI Healthcare Assistant
      `.trim();
      
      // Create downloadable file
      const blob = new Blob([reportContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `Health_Report_${patientInfo.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      alert("Health report downloaded successfully!");
    }, 1500);
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h2>📤 Share Report with Doctor</h2>
          <button onClick={onClose} className="modal-close">×</button>
        </div>

        <div className="share-report-content">
          {/* Patient Summary */}
          <div className="report-section">
            <h3>👤 Patient Summary</h3>
            <div className="report-details">
              <p><strong>Name:</strong> {patientInfo.name}</p>
              <p><strong>Age:</strong> {patientInfo.age} years</p>
              <p><strong>Condition:</strong> {patientInfo.condition}</p>
              <p><strong>Blood Group:</strong> {patientInfo.bloodGroup}</p>
              <p><strong>Gender:</strong> {patientInfo.gender}</p>
            </div>
          </div>

          {/* Medicines */}
          <div className="report-section">
            <h3>💊 Current Medications</h3>
            <div className="report-list">
              {medicines.map((med, index) => (
                <div key={index} className="report-item">
                  <strong>{med.name}</strong> - {med.dosage} ({med.time})
                  <br />
                  <small>Frequency: {med.frequency} | Duration: {med.duration}</small>
                  {med.instructions && <br />}
                  {med.instructions && <small>Instructions: {med.instructions}</small>}
                </div>
              ))}
            </div>
          </div>

          {/* Diet Plan */}
          <div className="report-section">
            <h3>🥗 Diet Plan</h3>
            <div className="diet-report-grid">
              <div>
                <h4>✅ Foods to Eat</h4>
                <ul>
                  {dietPlan.eat.map((food, i) => (
                    <li key={i}>{food}</li>
                  ))}
                </ul>
              </div>
              <div>
                <h4>❌ Foods to Avoid</h4>
                <ul>
                  {dietPlan.avoid.map((food, i) => (
                    <li key={i}>{food}</li>
                  ))}
                </ul>
              </div>
            </div>
            {dietPlan.mealPlan && (
              <div className="meal-plan-section">
                <h4>📋 Meal Plan</h4>
                <p><strong>Breakfast:</strong> {dietPlan.mealPlan.breakfast}</p>
                <p><strong>Lunch:</strong> {dietPlan.mealPlan.lunch}</p>
                <p><strong>Dinner:</strong> {dietPlan.mealPlan.dinner}</p>
                <p><strong>Snacks:</strong> {dietPlan.mealPlan.snacks}</p>
              </div>
            )}
          </div>

          {/* Prescription History */}
          <div className="report-section">
            <h3>📋 Recent Prescription History</h3>
            <div className="report-list">
              {prescriptionHistory.slice(0, 3).map((prescription, index) => (
                <div key={index} className="report-item">
                  <strong>{prescription.date}</strong> - {prescription.doctor}
                  <br />
                  <small>Condition: {prescription.condition}</small>
                  <br />
                  <small>Medicines: {prescription.medicines.join(', ')}</small>
                </div>
              ))}
            </div>
          </div>

          {/* Health Risks */}
          <div className="report-section">
            <h3>⚠️ Health Risks</h3>
            <div className="risk-summary">
              <p>• Monitor blood sugar levels regularly</p>
              <p>• Watch for possible drowsiness side effects</p>
              <p>• Limit salt intake for blood pressure control</p>
            </div>
          </div>
        </div>

        <div className="modal-actions">
          <button onClick={handleDownloadPDF} className="download-pdf-button" disabled={isDownloading}>
            {isDownloading ? "⏳ Downloading..." : "📥 Download PDF"}
          </button>
          <button onClick={onClose} className="close-modal-button">
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

export default ShareWithDoctor;
