import React, { useState, useContext } from "react";
import { getPatientInfo, getMedicines, getDietPlan, getPrescriptionHistory } from "../data/mockDatabase";
import { LanguageContext } from "../contexts/LanguageContext";

function ShareWithDoctor({ data, onClose }) {
  const { t } = useContext(LanguageContext);
  const [isDownloading, setIsDownloading] = useState(false);
  const [isSharing, setIsSharing] = useState(false);
  
  // Use mock database data if data prop is not provided
  const patientInfo = data?.patient || getPatientInfo();
  const medicines = data?.medicines || getMedicines();
  const dietPlan = data?.diet || getDietPlan();
  const prescriptionHistory = getPrescriptionHistory();

  const handleDownload = () => {
    setIsDownloading(true);
    setTimeout(() => {
      // Create plain text report
      const reportContent = `
========================================
HEALTH REPORT
Generated: ${new Date().toLocaleDateString()}
========================================

PATIENT INFORMATION
----------------------------------------
Name: ${patientInfo.name}
Age: ${patientInfo.age} years
Gender: ${patientInfo.gender}
Condition: ${patientInfo.condition}
Blood Group: ${patientInfo.bloodGroup}

CURRENT MEDICATIONS
----------------------------------------
${medicines.map((med, i) => `${i + 1}. ${med.name}
   Dosage: ${med.dosage}
   Frequency: ${med.frequency}
   Duration: ${med.duration}
   Time: ${med.time}
   ${med.instructions ? `Instructions: ${med.instructions}` : ''}
`).join('\n')}

DIET PLAN
----------------------------------------
Foods to Eat:
${dietPlan.eat.map(food => `  - ${food}`).join('\n')}

Foods to Avoid:
${dietPlan.avoid.map(food => `  - ${food}`).join('\n')}

${dietPlan.mealPlan ? `MEAL PLAN
----------------------------------------
Breakfast: ${dietPlan.mealPlan.breakfast}
Lunch: ${dietPlan.mealPlan.lunch}
Dinner: ${dietPlan.mealPlan.dinner}
Snacks: ${dietPlan.mealPlan.snacks}
` : ''}

HEALTH RISKS & WARNINGS
----------------------------------------
- Monitor blood sugar levels regularly
- Watch for possible drowsiness side effects
- Limit salt intake for blood pressure control

PRESCRIPTION HISTORY
----------------------------------------
${prescriptionHistory.slice(0, 3).map(p => `- ${p.date}: ${p.doctor} - ${p.condition}`).join('\n')}

========================================
Generated by Sahaay Healthcare Assistant
========================================
      `.trim();
      
      // Create downloadable file
      const blob = new Blob([reportContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `Health_Report_${patientInfo.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      setIsDownloading(false);
    }, 1500);
  };

  const handleShare = () => {
    setIsSharing(true);
    // Simulate sharing
    setTimeout(() => {
      setIsSharing(false);
      alert("Health report shared successfully!");
      onClose();
    }, 1500);
  };

  return (
    <div className="share-modal-overlay" onClick={onClose}>
      <div className="share-modal-content" onClick={(e) => e.stopPropagation()}>
        {/* Cross mark to close */}
        <button className="share-close-button" onClick={onClose}>×</button>
        
        {/* Plain text content */}
        <div className="share-text-content">
========================================
HEALTH REPORT
Generated: {new Date().toLocaleDateString()}
========================================

PATIENT INFORMATION
----------------------------------------
Name: {patientInfo.name}
Age: {patientInfo.age} years
Gender: {patientInfo.gender}
Condition: {patientInfo.condition}
Blood Group: {patientInfo.bloodGroup}

CURRENT MEDICATIONS
----------------------------------------
{medicines.map((med, i) => `${i + 1}. ${med.name}
   Dosage: ${med.dosage}
   Frequency: ${med.frequency}
   Duration: ${med.duration}
   Time: ${med.time}
   ${med.instructions ? `Instructions: ${med.instructions}` : ''}
`).join('\n')}

DIET PLAN
----------------------------------------
Foods to Eat:
{dietPlan.eat.map(food => `  - ${food}`).join('\n')}

Foods to Avoid:
{dietPlan.avoid.map(food => `  - ${food}`).join('\n')}

HEALTH RISKS
----------------------------------------
- Monitor blood sugar levels regularly
- Watch for possible drowsiness side effects
- Limit salt intake for blood pressure control

========================================
Generated by Sahaay Healthcare Assistant
========================================
        </div>
        
        {/* Action buttons */}
        <div className="share-action-buttons">
          <button 
            className="share-download-btn" 
            onClick={handleDownload}
            disabled={isDownloading}
          >
            {isDownloading ? 'Downloading...' : '📥 Download Chart'}
          </button>
          <button 
            className="share-btn" 
            onClick={handleShare}
            disabled={isSharing}
          >
            {isSharing ? 'Sharing...' : '📤 Share'}
          </button>
        </div>
      </div>
    </div>
  );
}

export default ShareWithDoctor;
